### ISSUE TITLE
Vector.__read__ do not support 3D geometries

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-chsdi3#1150]
See https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/models/vector/__init__.py#L55

**Comment by loicgasser** [comment]
```python
>>> from shapely.geometry import LineString
>>> from shapely.wkt import loads
>>> line_txt = '(632168.882 180514.191 3250.65,618345.024 180508.595 3247)'
>>> line_wkt = loads(line_txt)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ltgal/mf-chsdi3/buildout/eggs/Shapely-1.3.3-py2.7-linux-x86_64.egg/shapely/wkt.py", line 10, in loads
    return geos.WKTReader(geos.lgeos).read(data)
  File "/home/ltgal/mf-chsdi3/buildout/eggs/Shapely-1.3.3-py2.7-linux-x86_64.egg/shapely/geos.py", line 221, in read
    raise ReadingError("Could not create geometry because of errors "
shapely.geos.ReadingError: Could not create geometry because of errors while reading input.
>>> line_txt = 'LINESTRING (632168.882 180514.191 3250.65,618345.024 180508.595 3247)'                                                
>>> line_wkt = loads(line_txt)
>>> line_wkt.wkt
'LINESTRING Z (632168.882 180514.191 3250.65, 618345.024 180508.595 3247)'

>>> from shapely.wkb import dumps
>>> dumps(line_wkt)                                                                                                                   
'\x01\x02\x00\x00\x80\x02\x00\x00\x00\x06\x81\x95\xc3\xd1J#A\x0c\x02+\x87\x11\t\x06A\xcd\xcc\xcc\xccLe\xa9@^\xbaI\x0c\xd2\xde"A)\\\x8f\xc2\xe4\x08\x06A\x00\x00\x00\x00\x00^\xa9@'
>>> loads('(632168.882 180514.191 3250.65,618345.024 180508.595 3247)')                                                               
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ltgal/mf-chsdi3/buildout/eggs/Shapely-1.3.3-py2.7-linux-x86_64.egg/shapely/wkt.py", line 10, in loads
    return geos.WKTReader(geos.lgeos).read(data)
  File "/home/ltgal/mf-chsdi3/buildout/eggs/Shapely-1.3.3-py2.7-linux-x86_64.egg/shapely/geos.py", line 221, in read
    raise ReadingError("Could not create geometry because of errors "
shapely.geos.ReadingError: Could not create geometry because of errors while reading input.

```

This is exactly the same error we have on identify request. I suspect geoalchemy to kick the LINESTRING definition.
