### ISSUE TITLE
WMTS testing error

### ISSUE THREAD

**Issue by kandre** [geoadmin/mf-chsdi3#1370]
This is a recurrent error when testing wmts. One cannot open subprocesses like this.

Could you please adapt the code? 

ERROR: test_validate_wmtscapabilities (chsdi.tests.integration.test_wmtscapabilities.TestWmtsCapabilitiesView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/vhosts/mf-chsdi3/private/branch/kan_chsdi_emapis_entwaesserung/chsdi/tests/integration/test_wmtscapabilities.py", line 50, in test_validate_wmtscapabilities
    retcode = subprocess.call(["xmllint", "--noout", "--nocatalogs", "--schema", schema_url, f.name])
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1153, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

self.pid = os.fork()

**Comment by procrastinatio** [comment]
We have too much projects on this poor server... I see what I can do to improve the situation (beside deleting everything).

**Comment by kandre** [comment]
Ok great thank you
