### ISSUE TITLE
SearchServer 500 error

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-chsdi3#1601]
http://api3.geo.admin.ch/rest/services/api/SearchServer?lang=de&type=locations&searchText=Bussigny-pr%E8s-Lausanne%20jonction&

produces a 500:

[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136] mod_wsgi (pid=30722): Exception occurred processing WSGI script '/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/parts/modwsgi/wsgi'.
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136] Traceback (most recent call last):
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 242, in __call__
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]     response = self.invoke_subrequest(request, use_tweens=True)
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 217, in invoke_subrequest
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]     response = handle_request(request)
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]     response = handler(request)
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/pyramid_tm-0.12-py2.7.egg/pyramid_tm/__init__.py", line 99, in tm_tween
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]     reraise(*exc_info)
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/pyramid_tm-0.12-py2.7.egg/pyramid_tm/__init__.py", line 80, in tm_tween
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]     response = handler(request)
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 79, in handle_request
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]     has_listeners and notify(NewRequest(request))
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/registry.py", line 74, in notify
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]     [ _ for _ in self.subscribers(events, None) ]
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/zope.interface-4.0.5-py2.7-linux-x86_64.egg/zope/interface/registry.py", line 323, in subscribers
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]     return self.adapters.subscribers(objects, provided)
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/zope.interface-4.0.5-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 601, in subscribers
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]     subscription(*objects)
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/config/adapters.py", line 103, in derived_subscriber
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]     return subscriber(arg[0])
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/chsdi/subscribers.py", line 19, in add_localizer
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]     request._LOCALE_ = helpers.locale_negotiator(request)
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/chsdi/lib/helpers.py", line 74, in locale_negotiator
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]     lang = request.params.get('lang')
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/WebOb-1.4-py2.7.egg/webob/request.py", line 856, in params
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]     params = NestedMultiDict(self.GET, self.POST)
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/WebOb-1.4-py2.7.egg/webob/request.py", line 838, in GET
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]     vars = GetDict(data, env)
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/WebOb-1.4-py2.7.egg/webob/multidict.py", line 287, in __init__
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]     MultiDict.__init__(self, data)
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/WebOb-1.4-py2.7.egg/webob/multidict.py", line 38, in __init__
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]     items = list(args[0])
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/WebOb-1.4-py2.7.egg/webob/compat.py", line 125, in parse_qsl_text
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]     yield (x.decode(encoding), y.decode(encoding))
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]   File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136]     return codecs.utf_8_decode(input, errors, True)
[Wed Aug 12 11:23:40 2015] [error] [client 10.220.5.136] UnicodeDecodeError: 'utf8' codec can't decode byte 0xe8 in position 11: invalid continuation byte

**Comment by cedricmoullet** [comment]
@loicgasser How to avoid this error ?
