### ISSUE TITLE
print issues

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-chsdi3#1602]
On services create.json and printprogress, we can see occasionaly 503 and 500 errors.

It can be that these are related to these error logs:

[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61] mod_wsgi (pid=30722): Exception occurred processing WSGI script '/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/parts/modwsgi/wsgi'.
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61] Traceback (most recent call last):
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 242, in __call__
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]     response = self.invoke_subrequest(request, use_tweens=True)
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 217, in invoke_subrequest
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]     response = handle_request(request)
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]     response = handler(request)
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/pyramid_tm-0.12-py2.7.egg/pyramid_tm/__init__.py", line 99, in tm_tween
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]     reraise(*exc_info)
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/pyramid_tm-0.12-py2.7.egg/pyramid_tm/__init__.py", line 80, in tm_tween
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]     response = handler(request)
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 163, in handle_request
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]     response = view_callable(context, request)
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]     result = view(context, request)
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/buildout/eggs/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 477, in _class_requestonly_view
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]     response = getattr(inst, attr)()
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/chsdi/lib/decorators/__init__.py", line 25, in wrapped
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]     return f(self, *args, **kwargs)
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]   File "/var/www/vhosts/mf-chsdi3/private/chsdi/chsdi/views/printmulti.py", line 459, in print_progress
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]     data = json.load(data_file)
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]   File "/usr/lib/python2.7/json/__init__.py", line 278, in load
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]     **kw)
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]   File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]     return _default_decoder.decode(s)
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]   File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]   File "/usr/lib/python2.7/json/decoder.py", line 383, in raw_decode
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61]     raise ValueError("No JSON object could be decoded")
[Wed Aug 12 09:08:44 2015] [error] [client 10.220.6.61] ValueError: No JSON object could be decoded

[Wed Aug 12 10:29:42 2015] [error] [client 10.220.6.61] File does not exist: /var/cache/print/mapfish-print883017950496028388.pdf.printout

[Wed Aug 12 09:22:37 2015] [error] ajp_read_header: ajp_ilink_receive failed
[Wed Aug 12 09:22:37 2015] [error] (70007)The timeout specified has expired: proxy: dialog to (null) (*) failed

**Comment by cedricmoullet** [comment]
@procrastinatio @gjn can you see any potential explanation ?

**Comment by procrastinatio** [comment]
About half of error are 503 are a most probably communication issue between varnish and backend.

Error 500, many issues...

1/ Too many errors while gettings tiles 

```
2015-08-13 16:26:07,301 [tilesReader136] ERROR .mapfish.print.PDFCustomBlocks - Error while adding a PDF elementjava.io.IOException: Error (status=502) while reading the image from https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.pixelkarte-farbe/default/20151231/21781/22/244/

2015-08-13 22:55:50,537 [tilesReader35] ERROR     org.mapfish.print.PDFUtils - Server returned an error for https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.pixelkarte-farbe/default/20151231/21781/20/49/88.jpeg: Read timed out

2015-08-14 09:48:44,850 [tilesReader192] ERROR .mapfish.print.PDFCustomBlocks - Error while adding a PDF elementjava.io.IOException: Error (status=404) while reading the image from https://wmts.geo.admin.ch/1.0.0/ch.bafu.bundesinventare-hochmoore/default/20080721/21781/22/

2015-08-14 11:28:43,162 [tilesReader153] ERROR .mapfish.print.PDFCustomBlocks - Error while adding a PDF elementjava.io.IOException: Read timed out

```
2/ Zadara
I am less and less convinced zadata is a good solution for this kind of file. I have to prove it though.

3/ Socket Error

```

2015-08-14 06:44:37,861 [ajp-bio-8009-exec-43] ERROR h.print.servlet.BaseMapServlet - Error while generating PDF
java.io.IOException: Socket read failed
        at org.apache.coyote.ajp.AjpProcessor.read(AjpProcessor.java:313)
        at org.apache.coyote.ajp.AjpProcessor.readMessage(AjpProcessor.java:364)
        at org.apache.coyote.ajp.AjpProcessor.receive(AjpProcessor.java:331)
        at org.apache.coyote.ajp.AbstractAjpProcessor$SocketInputBuffer.doRead(AbstractAjpProcessor.java:1073)
        at org.apache.coyote.Request.doRead(Request.java:422)
        at org.apache.catalina.connector.InputBuffer.realReadBytes(InputBuffer.java:290)
        at org.apache.tomcat.util.buf.ByteChunk.substract(ByteChunk.java:431)
        at org.apache.catalina.connector.InputBuffer.read(InputBuffer.java:315)
        at org.apache.catalina.connector.CoyoteInputStream.read(CoyoteInputStream.java:200)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:154)
        at java.io.BufferedReader.read1(BufferedReader.java:205)
        at java.io.BufferedReader.read(BufferedReader.java:279)
        at java.io.Reader.read(Reader.java:100)
        at com.google.common.io.CharStreams.copy(CharStreams.java:176)
        at com.google.common.io.CharStreams.toStringBuilder(CharStreams.java:220)
        at com.google.common.io.CharStreams.toString(CharStreams.java:194)
        at org.mapfish.print.servlet.MapPrinterServlet.getSpecFromPostBody(MapPrinterServlet.java:232)
        at org.mapfish.print.servlet.MapPrinterServlet.createPDF(MapPrinterServlet.java:180)
        at org.mapfish.print.servlet.MapPrinterServlet.doPost(MapPrinterServlet.java:109)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:641)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
        at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:579)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)

```

**Comment by gjn** [comment]
Some errors might also be triggered by aborted print requests (our front-end allows to cancel prints). See related error for profile: https://github.com/geoadmin/mf-chsdi3/issues/1599
