### ISSUE TITLE
jenkins is not happy with koernermais

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-chsdi3#2147]
Hi @alcapat 
Could you please investigate why we have the following jenkins error:

```
======================================================================
FAIL: Failure: AssertionError (ch.blw.klimaeignung-koernermais)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/PR_chsdi3/workspace/.venv/local/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/loader.py", line 251, in generate
    for test in g():
  File "/var/lib/jenkins/jobs/PR_chsdi3/workspace/chsdi/tests/integration/test_layers.py", line 144, in test_all_htmlpopups
    for layer, feature, extended in lc.ilayersWithFeatures():
  File "/var/lib/jenkins/jobs/PR_chsdi3/workspace/chsdi/tests/integration/test_layers.py", line 82, in ilayersWithFeatures
    assert (models is not None and len(models) > 0), layer
AssertionError: ch.blw.klimaeignung-koernermais

======================================================================
FAIL: Failure: AssertionError (ch.blw.klimaeignung-koernermais)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/PR_chsdi3/workspace/.venv/local/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/loader.py", line 251, in generate
    for test in g():
  File "/var/lib/jenkins/jobs/PR_chsdi3/workspace/chsdi/tests/integration/test_layers.py", line 156, in test_all_ids_mapping
    for layerId, featureId, model, primaryKeyColumn in lc.ilayersAllModels():
  File "/var/lib/jenkins/jobs/PR_chsdi3/workspace/chsdi/tests/integration/test_layers.py", line 66, in ilayersAllModels
    assert (models is not None and len(models) > 0), layer
AssertionError: ch.blw.klimaeignung-koernermais
```

**Comment by gjn** [comment]
I think the error is on my side. For production (api3.geo.admin.ch job), we use the latest github release tag for the build and test. Unfortunately, I didn't create this tag yesterday after the deploy, but just this morning.

I've re-launched the test and I assume it will be good now. Sorry for the noise.
