### ISSUE TITLE
RSS feed generation keeps failing

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/mf-chsdi3#2255]
```

Creating the rss feed from releasenotes
.venv/bin/python scripts/rssFeedGen.py
Traceback (most recent call last):
  File "scripts/rssFeedGen.py", line 97, in <module>
    rss = rss.to_xml('utf-8')
  File "build/bdist.linux-x86_64/egg/PyRSS2Gen.py", line 39, in to_xml
  File "build/bdist.linux-x86_64/egg/PyRSS2Gen.py", line 34, in write_xml
  File "build/bdist.linux-x86_64/egg/PyRSS2Gen.py", line 380, in publish
  File "scripts/rssFeedGen.py", line 25, in publish
    PyRSS2Gen.RSSItem.publish(self, handler)
  File "build/bdist.linux-x86_64/egg/PyRSS2Gen.py", line 429, in publish
  File "scripts/rssFeedGen.py", line 28, in publish_extensions
    handler._out.write('<%s><![CDATA[%s]]></%s>' % ('description', self.do_not_autooutput_description, 'description'))
AttributeError: XMLGenerator instance has no attribute '_out'

```

**Comment by loicgasser** [comment]
This can be closed, pollution from Jessie instance and this is now fixed there anyway
