### ISSUE TITLE
Table column definition

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2319]
```
======================================================================
FAIL: chsdi.tests.integration.test_layers.test_all_ids_mapping(u'ch.swisstopo.geologie-gravimetrischer_atlas.metadata', u'GRAV-DRG-47', <class 'chsdi.models.vector.stopo.GravimetrischerAtlasMetadata'>, Column('s_map_number', Integer(), t
able=<view_gridstand_gravimetrie_atlas_metadata_shop>, primary_key=True, nullable=False))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ltgal/mf-chsdi3/.venv/local/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/ltgal/mf-chsdi3/chsdi/tests/integration/test_layers.py", line 154, in checkPrimaryKeyColumnTypeMapping
    pythonType, type(featureId), layerId, schema + '.' + model.__tablename__)
AssertionError: Expected <type 'int'>; Got: <type 'unicode'>; For layer ch.swisstopo.geologie-gravimetrischer_atlas.metadata and GeoTable geol.view_gridstand_gravimetrie_atlas_metadata_shop

======================================================================
FAIL: chsdi.tests.integration.test_layers.test_all_ids_mapping(u'ch.swisstopo.strassenkarte200_papier.metadata', u'6009', <class 'chsdi.models.vector.stopo.StrassenKarte200Metadata'>, Column('s_map_number', Integer(), table=<view_gridsta
nd_stk200>, primary_key=True, nullable=False))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ltgal/mf-chsdi3/.venv/local/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/ltgal/mf-chsdi3/chsdi/tests/integration/test_layers.py", line 154, in checkPrimaryKeyColumnTypeMapping
    pythonType, type(featureId), layerId, schema + '.' + model.__tablename__)
AssertionError: Expected <type 'int'>; Got: <type 'unicode'>; For layer ch.swisstopo.strassenkarte200_papier.metadata and GeoTable datenstand.view_gridstand_stk200
```

I don't know if it's a work in progress but could you please check @pfanguin ?

**Comment by pfanguin** [comment]
see : #2321
