### ISSUE TITLE
nose tests fail when we run it locally

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-chsdi3#2677]
For example:  
```
======================================================================
ERROR: chsdi.tests.integration.test_layers.test_all_identify(u'ch.bfe.windenergie-geschwindigkeit_h125',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ltteo/mf-chsdi3/.venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/ltteo/mf-chsdi3/chsdi/tests/integration/test_layers.py", line 123, in checkIdentify
    resp = self.testapp.get(link)
  File "/home/ltteo/mf-chsdi3/.venv/lib/python2.7/site-packages/webtest/app.py", line 327, in get
    expect_errors=expect_errors)
  File "/home/ltteo/mf-chsdi3/.venv/lib/python2.7/site-packages/webtest/app.py", line 636, in do_request
    self._check_status(status, res)
  File "/home/ltteo/mf-chsdi3/.venv/lib/python2.7/site-packages/webtest/app.py", line 668, in _check_status
    res)
AppError: Bad response: 500 Internal Server Error (not 200 OK or 3xx redirect for http://localhost/rest/services/all/MapServer/identify?geometry=558945.5,147956,559402,148103.5&geometryType=esriGeometryEnvelope&imageDisplay=500,600,96&mapExtent=558945.5,147956,559402,148103.5&tolerance=1&layers=all:ch.bfe.windenergie-geschwindigkeit_h125)
500 Internal Server Error

The server has either erred or is incapable of performing the requested operation.


Error during connection to the bucket S3ResponseError: 403 Forbidden

```

**Comment by oterral** [comment]
And if I run the url with my version I got:
```
{
"status": "error",
"code": 500,
"detail": "Error during connection to the table Profile \"ltteo_aws_admin\" not found!"
}
```

http://mf-chsdi3.dev.bgdi.ch/ltteo/rest/services/all/MapServer/identify?geometry=558945.5,147956,559402,148103.5&geometryType=esriGeometryEnvelope&imageDisplay=500,600,96&mapExtent=558945.5,147956,559402,148103.5&tolerance=1&layers=all:ch.bfe.windenergie-geschwindigkeit_h125

**Comment by loicgasser** [comment]
so add your profile, no? Works well for me...
