### ISSUE TITLE
Primary key wrong mapping

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2736]
```
======================================================================
FAIL: chsdi.tests.integration.test_layers.test_all_ids_mapping(u'ch.bafu.bundesinventare-moorlandschaften', 238, <class 'chsdi.models.vector.bafu.ML'>, Column('bgdi_id', Unicode(), table=<moorlandschaften>, primary_key=True, nullable=False))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/PR_chsdi3/.venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/var/lib/jenkins/workspace/PR_chsdi3/chsdi/tests/integration/test_layers.py", line 164, in checkPrimaryKeyColumnTypeMapping
    pythonType, type(featureId), layerId, schema + '.' + model.__tablename__)
AssertionError: Expected <type 'unicode'>; Got: <type 'int'>; For layer ch.bafu.bundesinventare-moorlandschaften and GeoTable bundinv.moorlandschaften
```

Could you please fix? Or maybe the data has not been deployed to dev?

**Comment by nadine-piveteau** [comment]
Uups thanks! Once more I have become aware of the need and the benefits of these tests!
Solved it [here](https://github.com/geoadmin/mf-chsdi3/pull/2739).

**Comment by loicgasser** [comment]
https://github.com/geoadmin/mf-chsdi3/pull/2739#pullrequestreview-80870356
