### ISSUE TITLE
Errors on ch.bfe.energiestaedte, ch.bfe.energiestaedte-2000watt-aufdemweg, ch.bfe.energiestaedte-2000watt-areale, ch.bfe.energiestaedte-energieregionen

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-chsdi3#2828]
Provided that we're deploying `ch.bfe.minergiegebaeude` next week and that it is in the same DB, deploy is gona be fun. Do you see why?
Could please fix this ASAP?

```
======================================================================

ERROR: chsdi.tests.integration.test_layers.test_all_searchable_layers(u'ch.bfe.energiestaedte-2000watt-aufdemweg',)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/.venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/chsdi/tests/integration/test_layers.py", line 153, in checkSearch

    resp = self.testapp.get(link, status=expectedStatus)

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/.venv/local/lib/python2.7/site-packages/webtest/app.py", line 327, in get

    expect_errors=expect_errors)

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/.venv/local/lib/python2.7/site-packages/webtest/app.py", line 636, in do_request

    self._check_status(status, res)

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/.venv/local/lib/python2.7/site-packages/webtest/app.py", line 671, in _check_status

    "Bad response: %s (not %s)", res_status, status)

AppError: Bad response: 200 OK (not 404)

-------------------- >> begin captured logging << --------------------

chsdi: DEBUG: route matched for url http://localhost/rest/services/all/SearchServer?features=ch.bfe.energiestaedte-2000watt-aufdemweg&bbox=600818.7808825106,197290.49919797093,601161.2808825106,197587.99919797093&type=featuresearch&searchText=dummy; route_name: 'search', path_info: u'/rest/services/all/SearchServer', pattern: '/rest/services/{map}/SearchServer', matchdict: {'map': u'all'}, predicates: ''

chsdi: DEBUG: debug_authorization of url http://localhost/rest/services/all/SearchServer?features=ch.bfe.energiestaedte-2000watt-aufdemweg&bbox=600818.7808825106,197290.49919797093,601161.2808825106,197587.99919797093&type=featuresearch&searchText=dummy (view name u'' against context <pyramid.traversal.DefaultRootFactory instance at 0x7fd4dedc8a28>): Allowed (no authorization policy in use)

--------------------- >> end captured logging << ---------------------



======================================================================

ERROR: chsdi.tests.integration.test_layers.test_all_searchable_layers(u'ch.bfe.energiestaedte-2000watt-areale',)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/.venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/chsdi/tests/integration/test_layers.py", line 153, in checkSearch

    resp = self.testapp.get(link, status=expectedStatus)

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/.venv/local/lib/python2.7/site-packages/webtest/app.py", line 327, in get

    expect_errors=expect_errors)

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/.venv/local/lib/python2.7/site-packages/webtest/app.py", line 636, in do_request

    self._check_status(status, res)

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/.venv/local/lib/python2.7/site-packages/webtest/app.py", line 671, in _check_status

    "Bad response: %s (not %s)", res_status, status)

AppError: Bad response: 200 OK (not 404)

-------------------- >> begin captured logging << --------------------

chsdi: DEBUG: route matched for url http://localhost/rest/services/all/SearchServer?features=ch.bfe.energiestaedte-2000watt-areale&bbox=600818.7808825106,197290.49919797093,601161.2808825106,197587.99919797093&type=featuresearch&searchText=dummy; route_name: 'search', path_info: u'/rest/services/all/SearchServer', pattern: '/rest/services/{map}/SearchServer', matchdict: {'map': u'all'}, predicates: ''

chsdi: DEBUG: debug_authorization of url http://localhost/rest/services/all/SearchServer?features=ch.bfe.energiestaedte-2000watt-areale&bbox=600818.7808825106,197290.49919797093,601161.2808825106,197587.99919797093&type=featuresearch&searchText=dummy (view name u'' against context <pyramid.traversal.DefaultRootFactory instance at 0x7fd4e7529e60>): Allowed (no authorization policy in use)

--------------------- >> end captured logging << ---------------------



======================================================================

ERROR: chsdi.tests.integration.test_layers.test_all_searchable_layers(u'ch.bfe.energiestaedte-energieregionen',)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/.venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/chsdi/tests/integration/test_layers.py", line 153, in checkSearch

    resp = self.testapp.get(link, status=expectedStatus)

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/.venv/local/lib/python2.7/site-packages/webtest/app.py", line 327, in get

    expect_errors=expect_errors)

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/.venv/local/lib/python2.7/site-packages/webtest/app.py", line 636, in do_request

    self._check_status(status, res)

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/.venv/local/lib/python2.7/site-packages/webtest/app.py", line 671, in _check_status

    "Bad response: %s (not %s)", res_status, status)

AppError: Bad response: 200 OK (not 404)

-------------------- >> begin captured logging << --------------------

chsdi: DEBUG: route matched for url http://localhost/rest/services/all/SearchServer?features=ch.bfe.energiestaedte-energieregionen&bbox=600818.7808825106,197290.49919797093,601161.2808825106,197587.99919797093&type=featuresearch&searchText=dummy; route_name: 'search', path_info: u'/rest/services/all/SearchServer', pattern: '/rest/services/{map}/SearchServer', matchdict: {'map': u'all'}, predicates: ''

chsdi: DEBUG: debug_authorization of url http://localhost/rest/services/all/SearchServer?features=ch.bfe.energiestaedte-energieregionen&bbox=600818.7808825106,197290.49919797093,601161.2808825106,197587.99919797093&type=featuresearch&searchText=dummy (view name u'' against context <pyramid.traversal.DefaultRootFactory instance at 0x7fd4e024d518>): Allowed (no authorization policy in use)

--------------------- >> end captured logging << ---------------------



======================================================================

ERROR: chsdi.tests.integration.test_layers.test_all_searchable_layers(u'ch.bfe.energiestaedte',)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/.venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/chsdi/tests/integration/test_layers.py", line 153, in checkSearch

    resp = self.testapp.get(link, status=expectedStatus)

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/.venv/local/lib/python2.7/site-packages/webtest/app.py", line 327, in get

    expect_errors=expect_errors)

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/.venv/local/lib/python2.7/site-packages/webtest/app.py", line 636, in do_request

    self._check_status(status, res)

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/.venv/local/lib/python2.7/site-packages/webtest/app.py", line 671, in _check_status

    "Bad response: %s (not %s)", res_status, status)

AppError: Bad response: 200 OK (not 404)

-------------------- >> begin captured logging << --------------------

chsdi: DEBUG: route matched for url http://localhost/rest/services/all/SearchServer?features=ch.bfe.energiestaedte&bbox=600818.7808825106,197290.49919797093,601161.2808825106,197587.99919797093&type=featuresearch&searchText=dummy; route_name: 'search', path_info: u'/rest/services/all/SearchServer', pattern: '/rest/services/{map}/SearchServer', matchdict: {'map': u'all'}, predicates: ''

chsdi: DEBUG: debug_authorization of url http://localhost/rest/services/all/SearchServer?features=ch.bfe.energiestaedte&bbox=600818.7808825106,197290.49919797093,601161.2808825106,197587.99919797093&type=featuresearch&searchText=dummy (view name u'' against context <pyramid.traversal.DefaultRootFactory instance at 0x7fd4dff53ab8>): Allowed (no authorization policy in use)

--------------------- >> end captured logging << ---------------------



======================================================================

FAIL: chsdi.tests.integration.test_layers.test_all_ids_mapping(u'ch.bfe.energiestaedte-2000watt-aufdemweg', None, <class 'chsdi.models.vector.uvek.EnergiestaedteAufdemweg2000watt'>, Column('bgdi_id', Integer(), table=<energiestaedte_aufdemweg_2000watt>, primary_key=True, nullable=False))

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/.venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/chsdi/tests/integration/test_layers.py", line 161, in checkPrimaryKeyColumnTypeMapping

    schema + '.' + model.__tablename__, layerId)

AssertionError: No feature was found in table bfe.energiestaedte_aufdemweg_2000watt for layer ch.bfe.energiestaedte-2000watt-aufdemweg



======================================================================

FAIL: chsdi.tests.integration.test_layers.test_all_ids_mapping(u'ch.bfe.energiestaedte-2000watt-areale', None, <class 'chsdi.models.vector.uvek.Energiestaedte2000wattAreale'>, Column('bgdi_id', Integer(), table=<energiestaedte_2000watt_areale>, primary_key=True, nullable=False))

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/.venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/chsdi/tests/integration/test_layers.py", line 161, in checkPrimaryKeyColumnTypeMapping

    schema + '.' + model.__tablename__, layerId)

AssertionError: No feature was found in table bfe.energiestaedte_2000watt_areale for layer ch.bfe.energiestaedte-2000watt-areale



======================================================================

FAIL: chsdi.tests.integration.test_layers.test_all_ids_mapping(u'ch.bfe.energiestaedte-energieregionen', None, <class 'chsdi.models.vector.uvek.EnergiestaedteRegionen'>, Column('bgdi_id', Integer(), table=<energiestaedte_energieregionen>, primary_key=True, nullable=False))

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/.venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/chsdi/tests/integration/test_layers.py", line 161, in checkPrimaryKeyColumnTypeMapping

    schema + '.' + model.__tablename__, layerId)

AssertionError: No feature was found in table bfe.energiestaedte_energieregionen for layer ch.bfe.energiestaedte-energieregionen



======================================================================

FAIL: chsdi.tests.integration.test_layers.test_all_ids_mapping(u'ch.bfe.energiestaedte', None, <class 'chsdi.models.vector.uvek.Energiestaedte'>, Column('bgdi_id', Integer(), table=<energiestaedte>, primary_key=True, nullable=False))

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/.venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/home/jenkins-slave/workspace/3_PR-2827-OO4QEYTMFVOIO75ADSGB/chsdi/tests/integration/test_layers.py", line 161, in checkPrimaryKeyColumnTypeMapping

    schema + '.' + model.__tablename__, layerId)

AssertionError: No feature was found in table bfe.energiestaedte for layer ch.bfe.energiestaedte
```

**Comment by AFoletti** [comment]
we will deploy just the table, not the DB.
But yes, this is strange. The 4 layers have an autoupdate mechanic and they are fine in both INT and PROD
I'll have a look on Monday first thing

**Comment by alcapat** [comment]
Sorry, but we need to deploy all the DB (uvek_master) because of a change in constraint 

_CONSTRAINT enforce_geotype_the_geom CHECK (**geometrytype(the_geom) = 'MULTIPOINT'::text OR** geometrytype(the_geom) = 'POINT'::text OR the_geom IS NULL),_

**Comment by AFoletti** [comment]
Thanks @alcapat for the hint.
Problem is solved but I do not really understand what caused it. I'll check in greater detail later

**Comment by loicgasser** [comment]
FYI
We will deploy `uvek_master` on Wednesday. If you haven't created new tables your changes will be deploy at the same tim,
