### ISSUE TITLE
OpenData Surveying tooltip does not work

### ISSUE THREAD

**Issue by AFoletti** [geoadmin/mf-chsdi3#3386]
**This is a PROD issue**

**How to reproduce:**
- Open the ch.swisstopo-vd.amtliche-vermessung layer [here](https://s.geo.admin.ch/875e81fe67)
- click on a polygon

**Result:**
- Identify works, higlight comes up
- htmlpopup request is broken

**From the error log:**
rest/services/ech/MapServer/ch.swisstopo-vd.amtliche-vermessung/155958223/htmlPopup?coord=2697750.0000000005,1179750&imageDisplay=1859,671,96&lang=de&mapExtent=2195250,1022250,3124750,1357750&sr=2056

`Traceback (most recent call last):
  File "/home/ltclm/mf-chsdi3/.venv/lib/python2.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__
    result = template.render_unicode(**system)
  File "/home/ltclm/mf-chsdi3/.venv/lib/python2.7/site-packages/mako/template.py", line 482, in render_unicode
    self, self.callable_, args, data, as_unicode=True
  File "/home/ltclm/mf-chsdi3/.venv/lib/python2.7/site-packages/mako/runtime.py", line 883, in _render
    **_kwargs_for_callable(callable_, data)
  File "/home/ltclm/mf-chsdi3/.venv/lib/python2.7/site-packages/mako/runtime.py", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/ltclm/mf-chsdi3/.venv/lib/python2.7/site-packages/mako/runtime.py", line 947, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/ltclm/mf-chsdi3/chsdi/templates/htmlpopup/base.mako", line 59, in render_body
    ${self.table_body(c, lang)}
  File "/home/ltclm/mf-chsdi3/chsdi/templates/htmlpopup/cadastralwebmap_opendata.mako", line 33, in render_table_body
    params = CadastralWebMapParams(request)
  File "/home/ltclm/mf-chsdi3/chsdi/templates/htmlpopup/cadastralwebmap_opendata.mako", line 30, in __init__
    self.imageDisplay = request.params.get('imageDisplay', defaultImageDisplay)
  File "/home/ltclm/mf-chsdi3/chsdi/lib/validation/identify.py", line 187, in imageDisplay
    if self.tolerance > 0 and not all(i > 0 for i in self._imageDisplay):
  File "/home/ltclm/mf-chsdi3/chsdi/lib/validation/identify.py", line 92, in tolerance
    return self._tolerance
AttributeError: 'CadastralWebMapParams' object has no attribute '_tolerance'`

I guess this is bound to [this commit](https://github.com/geoadmin/mf-chsdi3/commit/d14558764625cc444b05cb3734f8362671e27788) that has been deployed to prod last week.

@procrastinatio could you please have a look for a fix? Thanks!

**Comment by ltkum** [comment]
Issue is coming from the fact that the class CadastralWebMapParams is not calling its parent constructor, which has an attribute _tolerance. (This means that attribute is not defined when we try to call such classes, and since Imagedisplay creation is calling _tolerance, it crashes)

That class is defined in mf-chsdi3/chsdi/templates/htmlpopup/cadastralwebmap.mako  and  mf-chsdi3/chsdi/templates/htmlpopup/cadastralwebmap_opendata.mako

**Comment by AFoletti** [comment]
Thanks for analyzing and fixing this issue.
The PR is in my eyes good to go.

@boecklic : I think this is a good candidate for an emergency deploy. Up to you 😉

**Comment by davidoesch** [comment]
It is an emergency deploy candidate

**Comment by mariokeusen** [comment]
For an emergency deploy: please consider this pr here https://github.com/geoadmin/mf-chsdi3/pull/3337

**Comment by procrastinatio** [comment]
Please test... I have no problem merging my own PR without review, but it's not good practice.

**Comment by procrastinatio** [comment]
Deployed. Please test

**Comment by procrastinatio** [comment]
If ok, close.

**Comment by davidoesch** [comment]
@AFoletti @mariokeusen imho ok

**Comment by mariokeusen** [comment]
lgtm thanks

**Comment by AFoletti** [comment]
Sorry, was away from PC. Anyways, it is all good. Thanks for the fix

**Comment by procrastinatio** [comment]
Deployed with https://github.com/geoadmin/mf-chsdi3/releases/tag/r_200212.
So closing

**Comment by davidoesch** [comment]
Thx — now hit the slopes
